"""add indexes to FK columns

Revision ID: ec6c5cc82796
Revises: fa09d86e5e93
Create Date: 2026-06-07 19:32:59.734985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6c5cc82796'
down_revision: Union[str, None] = 'fa09d86e5e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_po_line_items_po_id'), 'po_line_items', ['po_id'], unique=False)
    op.create_index(op.f('ix_po_line_items_product_id'), 'po_line_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_history_product_id'), 'stock_history', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_history_product_id'), table_name='stock_history')
    op.drop_index(op.f('ix_po_line_items_product_id'), table_name='po_line_items')
    op.drop_index(op.f('ix_po_line_items_po_id'), table_name='po_line_items')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    # ### end Alembic commands ###
